Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,3 +63,10 @@ jobs:
         run: |
             cat nohup.out || echo "No logs found"
 
+      - name: 📄 Output Failed Test Reports
+        if: failure()
+        run: |
+              echo "=== Showing test failure reports ==="
+              cat ./APIAssignment/target/surefire-reports/*.txt || echo "No test report found"
+
+
